import axiosInstance from "../axisInstance";

// **************************** TICKET MANAGEMENT **************************** //
// Create Ticket
export const createTicket = async (selectedEntity, formData) => {
  const response = await axiosInstance.post(
    `create-ticket/${selectedEntity}`,
    formData,
    {
      headers: {
        "Content-Type": "application/json",
      },
    }
  );
  return response.data;
};

// Update Ticket
export const updateTicket = async (selectedEntity, id, formData) => {
  const response = await axiosInstance.put(
    `update-ticket/${selectedEntity}/${id}`,
    formData,
    {
      headers: {
        "Content-Type": "application/json",
      },
    }
  );
  return response.data;
};

// Allocate Ticket
export const allocateTicket = async (selectedEntity, id, formData) => {
  const response = await axiosInstance.put(
    `escalate-ticket/${selectedEntity}/${id}`,
    formData,
    {
      headers: {
        "Content-Type": "application/json",
      },
    }
  );
  return response.data;
};

// Delete Ticket
export const deleteTicket = async (id) => {
  const response = await axiosInstance.put(`delete-ticket/${id}`, {
    headers: {
      "Content-Type": "application/json",
    },
  });
  return response.data;
};

// Get Ticket Details by ID
export const getTicketDetailsById = async (id) => {
  const response = await axiosInstance.post(`get-ticket-details-by-id/${id}`, {
    headers: {
      "Content-Type": "application/json",
    },
  });
  return response.data;
};

// Get All Tickets Details
export const getAllTicketsDetails = async (selectedEntity, formData) => {
  const response = await axiosInstance.post(
    `get-all-tickets-details/${selectedEntity}`,
    formData,
    {
      headers: {
        "Content-Type": "application/json",
      },
    }
  );
  return response.data;
};

// Get All Tickets Generated By User
export const getAllTicketsGeneratedByUser = async (
  selectedEntity,
  id,
  formData
) => {
  const response = await axiosInstance.post(
    `get-all-ticket-generated-by-user/${selectedEntity}/${id}`,
    formData,
    {
      headers: {
        "Content-Type": "application/json",
      },
    }
  );
  return response.data;
};

// Get All Transfers List Approval Pending by User
export const getAllTicketsAllocatedToUser = async (
  selectedEntity,
  id,
  formData
) => {
  const response = await axiosInstance.post(
    `get-all-ticket-allocated-to-user/${selectedEntity}/${id}`,
    formData,
    {
      headers: {
        "Content-Type": "application/json",
      },
    }
  );
  return response.data;
};

// Approval for Ticket Actions
export const approvalForTicket = async (
  selectedEntity,
  id,
  user_id,
  formData
) => {
  const response = await axiosInstance.post(
    `approval-for-ticket/${selectedEntity}/${id}/${user_id}`,
    formData,
    {
      headers: {
        "Content-Type": "application/json",
      },
    }
  );
  return response.data;
};
