import { useEffect, useState } from "react";
import {
  getAllDepartments,
  getAllTicketCategory,
} from "../../../services/master_services/service";
import { toast } from "react-toastify";
import { HelpDeskContext } from "./helpDeskContext";
import {
  getAllEmployeeDetails,
  getEmployeeDetails,
} from "../../../services/employeeDetails_services/services";
import { useSelector } from "react-redux";
import {
  deleteTicket,
  getAllTicketsAllocatedToUser,
  getAllTicketsGeneratedByUser,
  getTicketDetailsById,
} from "../../../services/ticket_services/service";

export const HelpDeskProvider = ({ children }) => {
  const { userDetails } = useSelector((state) => state.auth);
  const [listing, setListing] = useState(null);
  const [loginUserData, setLoginUserData] = useState(null);
  const [approvalByMeListing, setApprovalByMeListing] = useState(null);
  const [data, setData] = useState(null);
  const [formVisibility, setFormVisibility] = useState(false);
  const [viewVisibility, setViewVisibility] = useState(false);
  const [viewModules, setViewModules] = useState(null);
  const [currentTab, setCurrentTab] = useState("my_requests");
  const [tabType, setTabType] = useState({
    name: "My Requests",
    value: "my_requests",
  });
  const [formType, setFormType] = useState("Add");
  const [componentType, setComponentType] = useState("listing");
  const [viewId, setViewId] = useState(null);
  const [updateId, setUpdateId] = useState(null);
  const [deleteId, setDeleteId] = useState(null);
  const [filter, setFilter] = useState({ ticket_category_id: "" });
  const [limit, setLimit] = useState(10);
  const [totalPages, setTotalPages] = useState(null);
  const [page, setPage] = useState(1);
  const [isLoading, setIsLoading] = useState(true);
  const [userOptions, setUserOptions] = useState([]);
  const [departmentOptions, setDepartmentOptions] = useState([]);
  const [ticketCategoryOptions, setTicketCategoryOptions] = useState([]);
  const [tabList, setTabList] = useState([
    { name: "My Requests", value: "my_requests" },
    { name: "Allocated to Me", value: "allocate_to_me" },
  ]);
  const [refreshTrigger, setRefreshTrigger] = useState(0);

  const refreshData = () => {
    setRefreshTrigger((prev) => prev + 1);
  };

  // Create the final filter based on tab type
  const getFinalFilter = () => {
    const baseFilter = { ...filter };

    const { ...cleanFilter } = baseFilter;

    if (tabType.value === "my_requests") {
      return {
        ...cleanFilter,
        created_for_dept_id: "",
      };
    } else if (tabType.value === "allocate_to_me") {
      return {
        ...cleanFilter,
        approver_status: "PENDING",
      };
    }

    return cleanFilter;
  };

  // Get All Requests Generated By Me
  const getAllTicketsGeneratedByMeData = async (id) => {
    try {
      setIsLoading(true);
      const finalFilter = getFinalFilter();
      const data = await getAllTicketsGeneratedByUser(id, {
        limit,
        page,
        filter: finalFilter,
      });

      if (data.success) {
        setListing(data.data);
        setTotalPages(data.pagination.totalPages);
      } else {
        setListing(null);
        setTotalPages(null);
      }
    } catch (error) {
      setListing(null);
      setTotalPages(null);
    } finally {
      setIsLoading(false);
    }
  };

  // Get All Tickets Allocated To Me
  const getAllTicketsAllocatedToMeData = async (id) => {
    try {
      setIsLoading(true);
      const finalFilter = getFinalFilter();
      const data = await getAllTicketsAllocatedToUser(id, {
        limit,
        page,
        filter: finalFilter,
      });

      if (data.success) {
        setListing(data.data);
        setTotalPages(data.pagination.totalPages);
      } else {
        setListing(null);
        setTotalPages(null);
      }
    } catch (error) {
      setListing(null);
      setTotalPages(null);
    } finally {
      setIsLoading(false);
    }
  };

  // Get Data By Id
  const getDataById = async (id) => {
    try {
      const response = await getTicketDetailsById(id);
      if (response.success) {
        setData(response.data[0]);
      } else {
        toast.error(response.message);
        throw new Error(response.message);
      }
    } catch (error) {
      setData(null);
    }
  };

  // Get Login User Data By Id
  const getLoginUserDataById = async (id) => {
    try {
      const response = await getEmployeeDetails(id);
      if (response.data.success) {
        setLoginUserData(response.data.data[0]);
      } else {
        toast.error(response.data.message);
        throw new Error(response.data.message);
      }
    } catch (error) {
      setLoginUserData(null);
    }
  };

  // Handle Form Visibility
  const handleFormVisibility = (visibility, formType) => {
    if (visibility === "open") {
      if (formType === "add") {
        setFormType("Add");
        setUpdateId(null);
        setData(null);
      } else if (formType === "update") {
        setFormType("Update");
      }
      setFormVisibility(true);
    } else if (visibility === "close") {
      setFormVisibility(false);
      setUpdateId(null);
      setData(null);
    }
  };

  // Handle View Visibility
  const handleViewVisibility = (type) => {
    if (type === "open") {
      setViewVisibility(true);
    } else if (type === "close") {
      setViewVisibility(false);
      setViewId(null);
    }
  };

  // Handle Component Type
  const handleComponentView = (type) => {
    setComponentType((prev) => (prev = type));
  };

  // Handle Component Type
  const handleComponentClose = () => {
    setData(null);
    setUpdateId(null);
    setViewId(null);
  };

  // Handle User Delete Functionality
  const handleDelete = async (id) => {
    try {
      const response = await deleteTicket(id);

      if (response.success) {
        toast.success(response.message);
        setDeleteId(null);
      } else {
        toast.error(response.message);
      }
    } catch (error) {
      toast.error(error.message);
    }
  };

  // Handle Set Limit
  const handleLimitChange = (e) => {
    e.preventDefault();
    setLimit(e.target.value);
  };

  // Handle Filter Value
  const handleChangeFilter = (type, e) => {
    if (type === "input") {
      const { name, value } = e.target;
      setFilter((prev) => ({ ...prev, [name]: value }));
    }

    if (type === "dropdown") {
      const { field, value } = e;
      setFilter((prev) => ({ ...prev, [field]: value }));
    }
  };

  // Handle Tabs Click
  const handleTabClick = (tabType) => {
    setTabType(tabType);
    setCurrentTab(tabType.value);
  };

  // Get All Ticket Category List
  const getAllTicketCategoryOptions = async () => {
    try {
      const response = await getAllTicketCategory({
        limit: 5000,
        page: "",
        filter: {
          name: "",
          priority: "",
        },
      });

      if (response.success) {
        setTicketCategoryOptions(
          response?.data.map((data) => ({
            value: data?.id,
            label: `${data?.ticket_category_name} - ${data?.ticket_category_code}`,
          }))
        );
      } else {
        throw new Error(response.message);
      }
    } catch (error) {
      setTicketCategoryOptions(null);
    }
  };

  // Get All Users List
  const getAllUsersOptions = async () => {
    try {
      const response = await getAllEmployeeDetails({
        limit: "",
        page: "",
        filter: {
          role_id: "",
          user_id: "",
        },
      });

      if (response.success) {
        setUserOptions(
          response?.data.map((data) => ({
            value: data?.id,
            label: data?.name,
          }))
        );
      } else {
        throw new Error(response.message);
      }
    } catch (error) {
      setUserOptions(null);
    }
  };

  // Get All Department List
  const getAllDepartmentOptions = async () => {
    try {
      const response = await getAllDepartments({
        limit: 500,
        page: "",
        filter: "",
      });

      if (response.success) {
        setDepartmentOptions(
          response?.data.map((data) => ({
            value: data?.id,
            label: data?.name,
          }))
        );
      } else {
        throw new Error(response.message);
      }
    } catch (error) {
      setDepartmentOptions(null);
    }
  };

  // Handle Form Close
  const handleFormClose = () => {
    if (currentTab === "my_requests") {
      handleTabClick({ name: "My Requests", value: "my_requests" });
    }

    if (currentTab === "allocate_to_me") {
      handleTabClick({
        name: "Allocated to Me",
        value: "allocate_to_me",
      });
    }
  };

  // For initial load and filter/pagination changes
  useEffect(() => {
    if (currentTab === "my_requests") {
      getAllTicketsGeneratedByMeData(userDetails?.id);
    } else if (currentTab === "allocate_to_me") {
      getAllTicketsAllocatedToMeData(userDetails?.id);
    }
  }, [
    limit,
    page,
    filter,
    refreshTrigger,
    currentTab,
    userDetails?.id,
    deleteId,
  ]);

  useEffect(() => {
    getAllDepartmentOptions();
    getAllUsersOptions();
    getAllTicketCategoryOptions();
  }, [updateId, deleteId]);

  // For update operations
  useEffect(() => {
    if (updateId || viewId) {
      const id = updateId || viewId;
      getDataById(id);
    }
  }, [updateId, viewId, tabType]);

  // For Get User Data operations
  useEffect(() => {
    if (userDetails) {
      const id = userDetails?.id;
      getLoginUserDataById(id);
    }
  }, [userDetails]);

  // For Delete operations
  useEffect(() => {
    if (deleteId) {
      const id = deleteId;
      handleDelete(id);
    }
  }, [deleteId]);

  const styledComponent = {
    control: (base) => ({
      ...base,
      minHeight: "32px",
      height: "32px",
      borderRadius: "0.375rem",
      borderColor: "#d1d5db", // gray-300
      fontSize: "0.875rem", // text-sm
      paddingLeft: "0.5rem", // px-2
      paddingRight: "0.5rem", // px-2
      "&:hover": {
        borderColor: "#d1d5db", // gray-300
      },
    }),
    dropdownIndicator: (base) => ({
      ...base,
      padding: "4px",
    }),
    clearIndicator: (base) => ({
      ...base,
      padding: "4px",
    }),
    valueContainer: (base) => ({
      ...base,
      padding: "0px",
    }),
    input: (base) => ({
      ...base,
      margin: "0px",
      paddingBottom: "0px",
      paddingTop: "0px",
    }),
    option: (base) => ({
      ...base,
      fontSize: "0.875rem", // text-sm
    }),
  };

  const formSelectStyles = {
    control: (base) => ({
      ...base,
      minHeight: "32px",
      borderRadius: "0.5rem",
      borderColor: "rgb(78, 79, 80)",
      fontSize: "0.8rem",
      paddingLeft: "0.75rem",
      paddingRight: "0.75rem",
      paddingTop: "0.5rem",
      paddingBottom: "0.5rem",
      "&:hover": {
        borderColor: "#d1d5db",
      },
    }),
    singleValue: (base) => ({
      ...base,
      fontSize: "0.8rem",
    }),
    menu: (base) => ({
      ...base,
      fontSize: "0.875rem",
    }),
    dropdownIndicator: (base) => ({
      ...base,
      padding: "3px",
    }),
    clearIndicator: (base) => ({
      ...base,
      padding: "2px",
    }),
    valueContainer: (base) => ({
      ...base,
      padding: "0px",
    }),
    input: (base) => ({
      ...base,
      margin: "0px",
      paddingBottom: "0px",
      paddingTop: "0px",
    }),
    option: (base) => ({
      ...base,
      fontSize: "0.8rem",
    }),
  };

  const contextValue = {
    listing,
    approvalByMeListing,
    viewModules,
    viewVisibility,
    formVisibility,
    formType,
    data,
    filter,
    limit,
    totalPages,
    page,
    isLoading,
    viewId,
    updateId,
    deleteId,
    tabType,
    currentTab,
    componentType,
    formSelectStyles,
    styledComponent,
    departmentOptions,
    userOptions,
    ticketCategoryOptions,
    tabList,
    loginUserData,
    refreshData,
    handleFormClose,
    getDataById,
    setUpdateId,
    setDeleteId,
    setPage,
    setViewId,
    setData,
    setViewVisibility,
    setDepartmentOptions,
    setComponentType,
    setTabList,
    setUserOptions,
    handleFormVisibility,
    handleTabClick,
    handleLimitChange,
    handleChangeFilter,
    handleViewVisibility,
    handleComponentView,
    handleComponentClose,
  };

  return (
    <HelpDeskContext.Provider value={contextValue}>
      {children}
    </HelpDeskContext.Provider>
  );
};
