import axiosInstance from "../axisInstance";

// **************************** EMPLOYEE MANAGEMENT **************************** //
// Create Employee
export const createEmployee = async (formData) => {
  const response = await axiosInstance.post("create-user", formData, {
    headers: {
      "Content-Type": "application/json",
    },
  });
  return response.data;
};

// Update Employee
export const updateEmployee = async (id, formData) => {
  const response = await axiosInstance.put(`update-user/${id}`, formData, {
    headers: {
      "Content-Type": "application/json",
    },
  });
  return response.data;
};

// Delete Employee
export const deleteEmployee = async (id) => {
  const response = await axiosInstance.put(`delete-user/${id}`, {
    headers: {
      "Content-Type": "application/json",
    },
  });
  return response.data;
};

// **************************** EMPLOYEE TRANSFER MASTER **************************** //
// Create Employee Transfer
export const createTransfer = async (formData) => {
  const response = await axiosInstance.post("create-transfer", formData, {
    headers: {
      "Content-Type": "application/json",
    },
  });
  return response.data;
};

// Update Employee Transfer
export const updateTransfer = async (id, formData) => {
  try {
    const response = await axiosInstance.put(`update-transfer/${id}`, formData);
    return response.data;
  } catch (error) {
    if (error.response) {
      return error.response.data;
    }
    throw error;
  }
};

// Get Employee Transfer by ID
export const getTransferById = async (id) => {
  const response = await axiosInstance.post(
    `get-transfer-details-by-id/${id}`,
    {
      headers: {
        "Content-Type": "application/json",
      },
    }
  );
  return response.data;
};

// Get All Transfers Generated By User
export const getAllTransfer = async (id, formData) => {
  const response = await axiosInstance.post(
    `get-all-transfer-generated-by-user/${id}`,
    formData,
    {
      headers: {
        "Content-Type": "application/json",
      },
    }
  );
  return response.data;
};

// Delete Employee Transfer
export const deleteTransfer = async (id) => {
  const response = await axiosInstance.put(`delete-transfer/${id}`, {
    headers: {
      "Content-Type": "application/json",
    },
  });
  return response.data;
};

// Get All Transfers List Approval Pending by User
export const getAllTransfersApprovalPendingByUser = async (id, formData) => {
  const response = await axiosInstance.post(
    `get-all-transfer-approval-pending-by-user/${id}`,
    formData,
    {
      headers: {
        "Content-Type": "application/json",
      },
    }
  );
  return response.data;
};

// Get All Transfers List Approved by User
export const getAllTransfersApprovedByUser = async (id, formData) => {
  const response = await axiosInstance.post(
    `get-all-transfer-approved-by-user/${id}`,
    formData,
    {
      headers: {
        "Content-Type": "application/json",
      },
    }
  );
  return response.data;
};

// Get All Transfers List Rejected by User
export const getAllTransfersRejectedByUser = async (id, formData) => {
  const response = await axiosInstance.post(
    `get-all-transfer-rejected-by-user/${id}`,
    formData,
    {
      headers: {
        "Content-Type": "application/json",
      },
    }
  );
  return response.data;
};

// Approval for Transfer Actions
export const approvalForTransfer = async (id, formData) => {
  const response = await axiosInstance.post(
    `approval-for-transfer/${id}`,
    formData,
    {
      headers: {
        "Content-Type": "application/json",
      },
    }
  );
  return response.data;
};

// **************************** EMPLOYEE ID CARD MANAGEMENT **************************** //
// Create ID Card
export const createIdCard = async (formData) => {
  const response = await axiosInstance.post(
    "create-employee-id-card",
    formData,
    {
      headers: {
        "Content-Type": "application/json",
      },
    }
  );
  return response.data;
};

// Update ID Card
export const updateIdCard = async (id, formData) => {
  const response = await axiosInstance.put(
    `update-employee-id-card/${id}`,
    formData,
    {
      headers: {
        "Content-Type": "application/json",
      },
    }
  );
  return response.data;
};

// Update Status
export const updateIdCardStatus = async (id) => {
  const response = await axiosInstance.put(
    `update-employee-id-card-status/${id}`,
    {
      headers: {
        "Content-Type": "application/json",
      },
    }
  );
  return response.data;
};

// Get ID Card by ID
export const getIdCardById = async (id) => {
  const response = await axiosInstance.post(
    `get-employee-id-card-details/${id}`,
    {
      headers: {
        "Content-Type": "application/json",
      },
    }
  );
  return response.data;
};

// Get All ID Card List
export const getAllIdCard = async (formData) => {
  const response = await axiosInstance.post(
    "get-all-employee-id-card-details",
    formData,
    {
      headers: {
        "Content-Type": "application/json",
      },
    }
  );
  return response.data;
};

// Delete ID Card
export const deleteIdCard = async (id) => {
  const response = await axiosInstance.put(`delete-employee-id-card/${id}`, {
    headers: {
      "Content-Type": "application/json",
    },
  });
  return response.data;
};
